##################################################################################
##################################################################################
##################################################################################
 #   _____ ______ _   _  _____  ____  _____   _____ 
 #  / ____|  ____| \ | |/ ____|/ __ \|  __ \ / ____|
 # | (___ | |__  |  \| | (___ | |  | | |__) | (___  
 #  \___ \|  __| | . ` |\___ \| |  | |  _  / \___ \ 
 #  ____) | |____| |\  |____) | |__| | | \ \ ____) |
 # |_____/|______|_| \_|_____/ \____/|_|  \_\_____/ 
sensor:
##################################################################################
   - platform: min_max  # https://www.home-assistant.io/integrations/min_max/
     name: "Température moyenne étage"
     type: mean
     entity_ids:
       - sensor.temperature_chambre_1
       - sensor.temperature_chambre_2
       - sensor.temperature_chambre_parents
       - sensor.temperature_douche


   - platform: min_max  # https://www.home-assistant.io/integrations/min_max/
     name: "Température moyenne extérieure"
     type: mean
     entity_ids:
       - sensor.temperature_anemometre
       - sensor.temperature_exterieure_allee
       - sensor.temperature_exterieure_terrasse

##################################################################################
##################################################################################
##################################################################################
 #  _____ _   _ _____  _    _ _______   _____       _______ ______ _______ _____ __  __ ______ 
 # |_   _| \ | |  __ \| |  | |__   __| |  __ \   /\|__   __|  ____|__   __|_   _|  \/  |  ____|
 #   | | |  \| | |__) | |  | |  | |    | |  | | /  \  | |  | |__     | |    | | | \  / | |__   
 #   | | | . ` |  ___/| |  | |  | |    | |  | |/ /\ \ | |  |  __|    | |    | | | |\/| |  __|  
 #  _| |_| |\  | |    | |__| |  | |    | |__| / ____ \| |  | |____   | |   _| |_| |  | | |____ 
 # |_____|_| \_|_|     \____/   |_|    |_____/_/    \_\_|  |______|  |_|  |_____|_|  |_|______|
input_datetime: 
# https://www.home-assistant.io/integrations/input_datetime/
##################################################################################
  night_cooling_last_notification_sent:
    has_date: true

##################################################################################
##################################################################################
##################################################################################
 #          _    _ _______ ____  __  __       _______ _____ ____  _   _  _____ 
 #     /\  | |  | |__   __/ __ \|  \/  |   /\|__   __|_   _/ __ \| \ | |/ ____|
 #    /  \ | |  | |  | | | |  | | \  / |  /  \  | |    | || |  | |  \| | (___  
 #   / /\ \| |  | |  | | | |  | | |\/| | / /\ \ | |    | || |  | | . ` |\___ \ 
 #  / ____ \ |__| |  | | | |__| | |  | |/ ____ \| |   _| || |__| | |\  |____) |
 # /_/    \_\____/   |_|  \____/|_|  |_/_/    \_\_|  |_____\____/|_| \_|_____/ 
automation:
# https://www.home-assistant.io/integrations/automation/
##################################################################################
  - alias: "rafraichissement nocturne"
    trigger:
      - platform: time_pattern
        minutes: '/5'
        seconds: 0
    condition:
      condition: and # toutes les conditions doivent être vraies "TRUE" avant que l'action ne soit exécutée.
      conditions:
      - condition: template
        value_template: '{{ now().month > 4 }}' # Starting May
      - condition: template
        value_template: '{{ now().month < 10 }}' # Ending October
      - condition: template
        value_template: "{{(states.sensor.temperature_moyenne_exterieure.state | float ) > 24 }}" # Température extérieure minimale pour nécessiter un rafraichissement nocture
      - condition: template
        value_template: "{{ states.sensor.temperature_moyenne_etage.state | float > (states.sensor.temperature_moyenne_exterieure.state | float + 2) }}" # +2 pour avoir un delta T suffisant pour operer un rafraichissement performant
      - condition: template
        value_template: '{{ now().hour > 18 }}' # seulement après 18h00
      - condition: template # une seule notification par jour 
        value_template: >
          {{
            not is_state_attr('input_datetime.night_cooling_last_notification_sent', 'day', now().day) 
          }}
    action:
      - service: notify.HA
        data_template:
          message: 'la Température intérieure {{ states.sensor.temperature_moyenne_etage.state | round | int }} degrés est superieure à la température extérieure {{ states.sensor.temperature_moyenne_exterieure.state | round | int }}degrés. Ouverture des fenêtres recommandée'

      - service: tts.google_say
        entity_id: "media_player.bureau, media_player.yamaha, media_player.salon"
        data_template:
          message: 'la Température intérieure {{ states.sensor.temperature_moyenne_etage.state | round | int }} degrés est superieure à la température extérieure {{ states.sensor.temperature_moyenne_exterieure.state | round | int }}degrés. Ouverture des fenêtres recommandée'


      - service: input_datetime.set_datetime # https://www.home-assistant.io/integrations/input_datetime/
        entity_id: input_datetime.night_cooling_last_notification_sent
        data_template:
          date: "{{ now().strftime('%Y-%m-%d') }}"
          
