# # https://github.com/papo-o/home-assistant-config/blob/master/integrations/notification_fin_rafraichissement_matinal.yaml
##################################################################################
##################################################################################
##################################################################################
 #  _____ _   _ _____  _    _ _______   _____       _______ ______ _______ _____ __  __ ______ 
 # |_   _| \ | |  __ \| |  | |__   __| |  __ \   /\|__   __|  ____|__   __|_   _|  \/  |  ____|
 #   | | |  \| | |__) | |  | |  | |    | |  | | /  \  | |  | |__     | |    | | | \  / | |__   
 #   | | | . ` |  ___/| |  | |  | |    | |  | |/ /\ \ | |  |  __|    | |    | | | |\/| |  __|  
 #  _| |_| |\  | |    | |__| |  | |    | |__| / ____ \| |  | |____   | |   _| |_| |  | | |____ 
 # |_____|_| \_|_|     \____/   |_|    |_____/_/    \_\_|  |______|  |_|  |_____|_|  |_|______|
input_datetime: 
# https://www.home-assistant.io/integrations/input_datetime/
##################################################################################
  morning_est_cooling_last_notification_sent:
    has_date: true
  morning_ouest_cooling_last_notification_sent:
    has_date: true
##################################################################################
##################################################################################
##################################################################################
 #          _    _ _______ ____  __  __       _______ _____ ____  _   _  _____ 
 #     /\  | |  | |__   __/ __ \|  \/  |   /\|__   __|_   _/ __ \| \ | |/ ____|
 #    /  \ | |  | |  | | | |  | | \  / |  /  \  | |    | || |  | |  \| | (___  
 #   / /\ \| |  | |  | | | |  | | |\/| | / /\ \ | |    | || |  | | . ` |\___ \ 
 #  / ____ \ |__| |  | | | |__| | |  | |/ ____ \| |   _| || |__| | |\  |____) |
 # /_/    \_\____/   |_|  \____/|_|  |_/_/    \_\_|  |_____\____/|_| \_|_____/ 
automation:
# https://www.home-assistant.io/integrations/automation/
##################################################################################
  - id: "rafraichissement matinal ouest"
    alias: "rafraichissement matinal ouest"
    trigger:
      - platform: time_pattern
        minutes: '/5'
        seconds: 0
    condition:
      condition: and # toutes les conditions doivent être vraies "TRUE" avant que l'action ne soit exécutée.
      conditions:
      - condition: template
        value_template: '{{ now().month > 4 }}' # Starting May
      - condition: template
        value_template: '{{ now().month < 10 }}' # Ending October
      - condition: template
        value_template: "{{ states('binary_sensor.fenetres_ouest') == 'on'}}"
      - condition: template
        value_template: "{{ states('sensor.temperature_moyenne_rdc') | float(0) < (states('sensor.temperature_bal') | float(0) )}}" # +2 pour avoir un delta T suffisant pour operer un rafraichissement performant
      - condition: template
        value_template: '{{ now().hour > 7 }}' # seulement après 18h00
      - condition: template
        value_template: '{{ now().hour < 10 }}' # jusqu'à 23h00
      - condition: template # une seule notification par jour 
        value_template: >
          {{
            not is_state_attr('input_datetime.morning_ouest_cooling_last_notification_sent', 'day', now().day) 
          }}
    action:
      - service: input_datetime.set_datetime # https://www.home-assistant.io/integrations/input_datetime/
        entity_id: input_datetime.morning_ouest_cooling_last_notification_sent
        data:
          date: "{{ now().strftime('%Y-%m-%d') }}"
      - service: notify.telegram
        data:
          message: >-
            "la Température extérieure à l'ouest
            {{ states('sensor.temperature_bal') | round | int }} 
            degrés est superieure à la température intérieure 
            {{ states('sensor.temperature_moyenne_rdc') | round | int }}
            degrés. Fermeture des fenêtres recommandée"
      - service: notify.echo_salon
        data:
          message: >- 
            "la Température extérieure à l'ouest
            {{ states('sensor.temperature_bal') | round | int }} 
            degrés est superieure à la température intérieure 
            {{ states('sensor.temperature_moyenne_rdc') | round | int }}
            degrés. Fermeture des fenêtres recommandée"
      - service: notify.echo_bureau
        data:
          message: >-
            "la Température extérieure à l'ouest
            {{ states('sensor.temperature_bal') | round | int }} 
            degrés est superieure à la température intérieure 
            {{ states('sensor.temperature_moyenne_rdc') | round | int }}
            degrés. Fermeture des fenêtres recommandée"
      - service: notify.echo_cuisine
        data:
          message: >-
            "la Température extérieure à l'ouest
            {{ states('sensor.temperature_bal') | round | int }} 
            degrés est superieure à la température intérieure 
            {{ states('sensor.temperature_moyenne_rdc') | round | int }}
            degrés. Fermeture des fenêtres recommandée"

  - id: "rafraichissement matinal est"
    alias: "rafraichissement matinal est"
    trigger:
      - platform: time_pattern
        minutes: '/5'
        seconds: 0
    condition:
      condition: and # toutes les conditions doivent être vraies "TRUE" avant que l'action ne soit exécutée.
      conditions:
      - condition: template
        value_template: '{{ now().month > 4 }}' # Starting May
      - condition: template
        value_template: '{{ now().month < 10 }}' # Ending October
      - condition: template
        value_template: "{{ states('binary_sensor.fenetres_est') == 'on'}}"
      - condition: template
        value_template: "{{ states('sensor.temperature_moyenne_rdc') | float(0) < (states('sensor.temperature_moyenne_terrasse') | float(0) ) }}" # +2 pour avoir un delta T suffisant pour operer un rafraichissement performant
      - condition: template
        value_template: '{{ now().hour > 7 }}' # seulement après 18h00
      - condition: template
        value_template: '{{ now().hour < 10 }}' # jusqu'à 23h00
      - condition: template # une seule notification par jour 
        value_template: >
          {{
            not is_state_attr('input_datetime.morning_est_cooling_last_notification_sent', 'day', now().day) 
          }}

    action:
      - service: input_datetime.set_datetime # https://www.home-assistant.io/integrations/input_datetime/
        entity_id: input_datetime.morning_est_cooling_last_notification_sent
        data:
          date: "{{ now().strftime('%Y-%m-%d') }}"
      - service: notify.telegram
        data:
          message: >-
            "la Température extérieure à l'est
            {{ states('sensor.temperature_moyenne_terrasse') | round | int }} 
            degrés est superieure à la température intérieure 
            {{ states('sensor.temperature_moyenne_rdc') | round | int }}
            degrés. Fermeture des fenêtres recommandée"
      - service: notify.echo_salon
        data:
          message: >- 
            "la Température extérieure à l'est
            {{ states('sensor.temperature_moyenne_terrasse') | round | int }} 
            degrés est superieure à la température intérieure 
            {{ states('sensor.temperature_moyenne_rdc') | round | int }}
            degrés. Fermeture des fenêtres recommandée"
      - service: notify.echo_bureau
        data:
          message: >-
            "la Température extérieure à l'est
            {{ states('sensor.temperature_moyenne_terrasse') | round | int }} 
            degrés est superieure à la température intérieure 
            {{ states('sensor.temperature_moyenne_rdc') | round | int }}
            degrés. Fermeture des fenêtres recommandée"
      - service: notify.echo_cuisine
        data:
          message: >-
            "la Température extérieure à l'est
            {{ states('sensor.temperature_moyenne_terrasse') | round | int }} 
            degrés est superieure à la température intérieure 
            {{ states('sensor.temperature_moyenne_rdc') | round | int }}
            degrés. Fermeture des fenêtres recommandée"